### ISSUE TITLE
Ошибка компиляции для платы LOLIN(WEMOS) D1 R2 & mini

### ISSUE THREAD

**Issue by ev-utkin** [AlexGyver/FireFX#2]
Добрый день.

При компиляции для WEMOS D1 mini возникают следующие ошибки. Библиотеки все вроде бы свежие, копировал с полной заменой скачаные с гитхаба. Просьба помочь с решением:

In file included from C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h:33:0,

                 from C:\Users\ev.utkin-nb\Documents\Arduino\fireLinePerlin\fireLinePerlin.ino:22:

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h: In function 'void WS2812B_sendData(uint16_t*, uint16_t, uint8_t, uint8_t*, uint8_t*, uint8_t)':

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:51:12: error: 'SREG' was not declared in this scope

  sreg_prev=SREG;

            ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:98:4: error: expected ')' before '_DELAY_'

    _DELAY_                      // основная задержка

    ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'counter'

    );

     ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'set_hi'

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'data'

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'set_lo'

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'data'

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'counter'

In file included from C:\Users\ev.utkin-nb\Documents\Arduino\fireLinePerlin\fireLinePerlin.ino:22:0:

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h: In constructor 'microLED::microLED(LEDdata*, int, byte)':

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h:186:14: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'const volatile uint8_t* {aka const volatile unsigned char*}' in assignment

  ws2812_port = portOutputRegister(digitalPinToPort(pin));

              ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h:187:18: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment

  ws2812_port_reg = portModeRegister(digitalPinToPort(pin));

                  ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h: In constructor 'microLED::microLED(LEDdata*, byte, byte, byte, M_type, M_connection, M_dir)':

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h:195:14: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'const volatile uint8_t* {aka const volatile unsigned char*}' in assignment

  ws2812_port = portOutputRegister(digitalPinToPort(pin));

              ^

C:\Users\ev.utkin-nb\Documents\Arduino\libraries\microLED/microLED.h:196:18: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment

  ws2812_port_reg = portModeRegister(digitalPinToPort(pin));

                  ^

exit status 1

**Comment by AlexGyver** [comment]
библиотека microLED работает только для AVR

**Comment by ev-utkin** [comment]
> 
> 
> библиотека microLED работает только для AVR

Ясно, спасибо. Доработка под ESP8266 планируется?

**Comment by AlexGyver** [comment]
Скорее всего нет, есп - ебанина

**Comment by Re1ic** [comment]
Та же беда с платами Дигиспарк

Поддержка Тини 85 планируется?

**Comment by AlexGyver** [comment]
тини85 должна работать

**Comment by Re1ic** [comment]
Arduino: 1.8.12 (Windows Store 1.8.33.0) (Windows 10), Плата:"Digispark (Default - 16.5mhz)"

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\Relic\Documents\ArduinoData\packages -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\Relic\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\Relic\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10812 -build-path C:\Users\Relic\AppData\Local\Temp\arduino_build_476837 -warnings=none -build-cache C:\Users\Relic\AppData\Local\Temp\arduino_cache_529613 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Relic\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.avr-gcc-4.8.1-arduino5.path=C:\Users\Relic\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.micronucleus.path=C:\Users\Relic\Documents\ArduinoData\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.micronucleus-2.0a4.path=C:\Users\Relic\Documents\ArduinoData\packages\digistump\tools\micronucleus\2.0a4 -verbose C:\Users\Relic\Downloads\FireFX-master\FireFX-master\firmware\Адреска\fireLine\fireLine.ino
C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\arduino-builder -compile -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\Relic\Documents\ArduinoData\packages -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\Relic\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\Relic\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10812 -build-path C:\Users\Relic\AppData\Local\Temp\arduino_build_476837 -warnings=none -build-cache C:\Users\Relic\AppData\Local\Temp\arduino_cache_529613 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Relic\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.avr-gcc-4.8.1-arduino5.path=C:\Users\Relic\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.micronucleus.path=C:\Users\Relic\Documents\ArduinoData\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.micronucleus-2.0a4.path=C:\Users\Relic\Documents\ArduinoData\packages\digistump\tools\micronucleus\2.0a4 -verbose C:\Users\Relic\Downloads\FireFX-master\FireFX-master\firmware\Адреска\fireLine\fireLine.ino
Using board 'digispark-tiny' from platform in folder: C:\Users\Relic\Documents\ArduinoData\packages\digistump\hardware\avr\1.6.7
Using core 'tiny' from platform in folder: C:\Users\Relic\Documents\ArduinoData\packages\digistump\hardware\avr\1.6.7
Detecting libraries used...
"C:\\Users\\Relic\\Documents\\ArduinoData\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10812 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\sketch\\fireLine.ino.cpp" -o nul
Alternatives for microLED.h: [microLED@2.1]
ResolveLibrary(microLED.h)
  -> candidates: [microLED@2.1]
"C:\\Users\\Relic\\Documents\\ArduinoData\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10812 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\Relic\\Documents\\Arduino\\libraries\\microLED" "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\sketch\\fireLine.ino.cpp" -o nul
Generating function prototypes...
"C:\\Users\\Relic\\Documents\\ArduinoData\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10812 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\Relic\\Documents\\Arduino\\libraries\\microLED" "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\sketch\\fireLine.ino.cpp" -o "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files\\WindowsApps\\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Компиляция скетча...
"C:\\Users\\Relic\\Documents\\ArduinoData\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10812 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\Relic\\Documents\\ArduinoData\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\Relic\\Documents\\Arduino\\libraries\\microLED" "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\sketch\\fireLine.ino.cpp" -o "C:\\Users\\Relic\\AppData\\Local\\Temp\\arduino_build_476837\\sketch\\fireLine.ino.cpp.o"
In file included from C:\Users\Relic\Documents\Arduino\libraries\microLED/microLED.h:33:0,

                 from C:\Users\Relic\Downloads\FireFX-master\FireFX-master\firmware\Адреска\fireLine\fireLine.ino:25:

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h: In function 'void WS2812B_sendData(uint8_t*, uint16_t, uint8_t, uint8_t*, uint8_t*, uint8_t)':

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:98:4: error: expected ')' before '_DELAY_'

    _DELAY_                      // основная задержка

    ^

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'counter'

    );

     ^

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'set_hi'

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'data'

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'set_lo'

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'data'

C:\Users\Relic\Documents\Arduino\libraries\microLED/ws2812_send.h:105:5: error: undefined named operand 'counter'

Используем библиотеку microLED версии 2.1 из папки: C:\Users\Relic\Documents\Arduino\libraries\microLED 
exit status 1
Ошибка компиляции для платы Digispark (Default - 16.5mhz).

**Comment by Re1ic** [comment]
Вот.

**Comment by AlexGyver** [comment]
корень проблемы кажется в том, что у дигиспарк настроен клок на 16.5 Мгц, а в библиотеке нет такого варианта и часть кода пропадает на этапе компиляции. Если работать чисто с тини85, то всё ок. Починим попробуем  когда нибудь..

**Comment by Re1ic** [comment]
Понял, спасибо. Будем подождать.

**Comment by Romanius614** [comment]
Доброй ночи. 
Не получается подключить лампу, следующая ошибка.

Arduino: 1.8.12 (Windows Store 1.8.33.0) (Windows 10), Плата:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\Роман\Downloads\GyverLamp-master\GyverLamp-master\firmware\GyverLamp_v1.5.5\GyverLamp_v1.5.5.ino:97:0:

C:\Users\�����\Documents\Arduino\libraries\FastLED-3.2.9/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.009

 #    pragma message "FastLED version 3.002.009"

                     ^

In file included from C:\Users\�����\Documents\Arduino\libraries\FastLED-3.2.9/FastLED.h:65:0,

                 from C:\Users\Роман\Downloads\GyverLamp-master\GyverLamp-master\firmware\GyverLamp_v1.5.5\GyverLamp_v1.5.5.ino:97:

C:\Users\�����\Documents\Arduino\libraries\FastLED-3.2.9/fastspi.h:115:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Users\�����\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.0/tools/sdk/libc/xtensa-lx106-elf/include/sys/stdio.h:6:0,

                 from C:\Users\�����\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.0/tools/sdk/libc/xtensa-lx106-elf/include/stdio.h:63,

                 from C:\Users\�����\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.0\cores\esp8266/Arduino.h:32,

                 from sketch\GyverLamp_v1.5.5.ino.cpp:1:

C:\Users\�����\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.0/tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h:25:130: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

   #define PROGMEM __attribute__((section( "\".irom.text." __FILE__ "." __STRINGIZE(__LINE__) "."  __STRINGIZE(__COUNTER__) "\"")))

                                                                                                                                  ^

C:\Users\�����\Documents\Arduino\libraries\WiFiManager/WiFiManager.h:25:24: note: in expansion of macro 'PROGMEM'

 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

                        ^

In file included from C:\Users\Роман\Downloads\GyverLamp-master\GyverLamp-master\firmware\GyverLamp_v1.5.5\GyverLamp_v1.5.5.ino:100:0:

C:\Users\�����\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.0\libraries\ESP8266WebServer\src/ESP8266WebServer.h:34:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                       ^

exit status 1
Ошибка компиляции для платы LOLIN(WEMOS) D1 R2 & mini.

Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"

Что было не верно сделано? Заранее спасибо!

**Comment by mplusor** [comment]
Аналогичная ошибка, как и у предыдущего комментатора

C:\Users\Home\Desktop\arduino-PR-beta1.9-BUILD-119\libraries\WiFiManager/WiFiManager.h:25:117: error: 'const char HTTP_HEAD []' redeclared as different kind of symbol

 const char HTTP_HEAD[] PROGMEM            = "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\"/><title>{v}</title>";

                                                                                                                     ^

In file included from C:\Users\Home\Desktop\Тимофеи\GyverLamp_v1.5.5\GyverLamp_v1.5.5.ino:100:0:

C:\Users\Home\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WebServer\src/ESP8266WebServer.h:34:39: error: previous declaration of 'HTTPMethod HTTP_HEAD'

 enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

                                       ^

Помогите поправить пожалуйста.

**Comment by AlexGyver** [comment]
Проект сделан под avr arduino, на платах есп не заведется и нужно переписывать

**Comment by poezd-oks** [comment]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000afc (most recent call first):
exit status 3
C:\Program Files (x86)\Arduino\arduino-builder возвратил 3
Ошибка компиляции для платы LOLIN(WEMOS) D1 R2 & mini.
Я вас приветствую.У меня такая проблема.Что делать,куда глянуть,как исправить.IDE  переустанавливал,ни чего не изменилось.

**Comment by Joker-lab11** [comment]
Скетч использует 300916 байт (28%) памяти устройства. Всего доступно 1044464 байт.
Глобальные переменные используют 28236 байт (34%) динамической памяти, оставляя 53684 байт для локальных переменных. Максимум: 81920 байт.
esptool.py v2.8
Serial port COM3
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/User/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 2889, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:/Users/User/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/esptool\esptool.py", line 249, in __init__
    self._port.write_timeout = DEFAULT_SERIAL_WRITE_TIMEOUT
  File "C:/Users/User/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/pyserial\serial\serialutil.py", line 388, in write_timeout
    self._reconfigure_port()
  File "C:/Users/User/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.4/tools/pyserial\serial\serialwin32.py", line 222, in _reconfigure_port
    'Original message: {!r}'.format(ctypes.WinError()))
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, '�������������� � ������� ���������� �� ��������.', None, 31)
Не удалась загрузка: ошибка при загрузке: exit status 1 

скетч переделывал с помощью нейронки т.к оригинальный не хотел грузиться и вылезало куча ошибок

[лампы.txt](https://github.com/user-attachments/files/19262864/default.txt)

Драйвера переустанавливал 
провод менял 
подскажите пожалуйста что делать?

**Comment by GyverLibs** [comment]
Здесь нет ошибки компиляции

**Comment by Joker-lab11** [comment]
> Здесь нет ошибки компиляции

а что же это может быть? и как это исправить?

**Comment by GyverLibs** [comment]
Написано же - ошибка загрузки. Читать гайд для новичков
